### ISSUE TITLE
BUG: August Month

### ISSUE THREAD

**Issue by DandyReyes** [USUGraffix/client#134]
When you first enter the calendar, August doesn't have all the events but when you click another month and come back, you see the event. So it is successfully grabbing data from presence but not populating in the event card for some reason.

**Comment by StewartMckenzie** [comment]
on line 305 
  const lastDay = new Date(y, m + 1, 0); assigns the last day of a month but at 12am in the morning
Changed to 
  const lastDay = new Date(y, m + 1, 0,24); so that you get the full day
