### ISSUE TITLE
Calendar: Social Media Handles

### ISSUE THREAD

**Issue by DandyReyes** [USUGraffix/client#142]
- [ ] Get Social Media Handles
- [ ] Add Social Media Handles to code

We are adding the Social Media Handles to 3 departments outside of the U-SU and one for Recreation in U-SU.

Dreamers Resource Center:
- IG: Calstateladreamers
- FB: csuladreamers

Student Health Center:
- IG: CalStateLASHAC

Career Center:
- calstatelacareercenter
- calstatelacareercenter

Recreation:
- CalStateLA_Rec

**Comment by StewartMckenzie** [comment]
Need a way to differentiate CSULA Rec from USU Rec

**Comment by StewartMckenzie** [comment]
I was mistaken CalStateLA_Rec is in fact our USU recreation! That social media link is already created.
