### ISSUE TITLE
Calendar: Event Titles

### ISSUE THREAD

**Issue by DandyReyes** [USUGraffix/client#145]
There is some instances where you need to have the a word from Event Title `All Caps`

| Before | After|
|-------|-------|
|*Fsl* House Party|*FSL* Party|
|Cal State *La*|Cal State *LA*|

**Comment by StewartMckenzie** [comment]
On line 5 I create an array with all possible acronyms like FSL and on 307 I map the array checking that acronym against the event titles using a regex and replacing where needed
