### ISSUE TITLE
BUG: Calendar page

### ISSUE THREAD

**Issue by DandyReyes** [USUGraffix/client#147]
When you first enter the calendar page, September is sorted correctly but it has every event for the semester. But when you click another month and come back to September then you will notice that it only has September on it.

**Comment by StewartMckenzie** [comment]
On line 361 I was not actually comparing the event dates to the selected month
I changed the code to the below where m is a global variable for a number representing the current month
      eventsList.map((event) => {
        if (event.getAttribute('data-month') == m )
          cardSection.append(event);
      });
